// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Cv93uwQqABRJ9dYS2JvhqtkizEE5MhY',
    appId: '1:489774219154:web:2f3b34945a16d186ec0b4b',
    messagingSenderId: '489774219154',
    projectId: 'fyp-12e7a',
    authDomain: 'fyp-12e7a.firebaseapp.com',
    databaseURL: 'https://fyp-12e7a-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-12e7a.appspot.com',
    measurementId: 'G-9B9CKQDN89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoqrybXF-ti-FQYsadKCkIpv1LVqvIuhc',
    appId: '1:489774219154:android:22c2e5a98f9c1f05ec0b4b',
    messagingSenderId: '489774219154',
    projectId: 'fyp-12e7a',
    databaseURL: 'https://fyp-12e7a-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-12e7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBD5Of5i5Nv27NjmiR_HVTMK1Cv-UfIq4',
    appId: '1:489774219154:ios:580f5f7db0aade1bec0b4b',
    messagingSenderId: '489774219154',
    projectId: 'fyp-12e7a',
    databaseURL: 'https://fyp-12e7a-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-12e7a.appspot.com',
    androidClientId: '489774219154-0dm5puqs8hs31dmvmf3tphopjjjtevkp.apps.googleusercontent.com',
    iosClientId: '489774219154-eajs5b7um95r4v756frlkh96as08304q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBD5Of5i5Nv27NjmiR_HVTMK1Cv-UfIq4',
    appId: '1:489774219154:ios:580f5f7db0aade1bec0b4b',
    messagingSenderId: '489774219154',
    projectId: 'fyp-12e7a',
    databaseURL: 'https://fyp-12e7a-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-12e7a.appspot.com',
    androidClientId: '489774219154-0dm5puqs8hs31dmvmf3tphopjjjtevkp.apps.googleusercontent.com',
    iosClientId: '489774219154-eajs5b7um95r4v756frlkh96as08304q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ93mkW-h9syuJ4rsjUQLN_0JielYxHLQ',
    appId: '1:489774219154:web:305ac2d80cd9a1d8ec0b4b',
    messagingSenderId: '489774219154',
    projectId: 'fyp-12e7a',
    authDomain: 'fyp-12e7a.firebaseapp.com',
    databaseURL: 'https://fyp-12e7a-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-12e7a.appspot.com',
    measurementId: 'G-2XYHFW0M8F',
  );
}
